server:
  servlet:
    context-path: /employeePortalWithSpringBoot
spring:
  datasource: 
    url: jdbc:mysql://localhost/employeePortal
    username: root
    password: password
    driver-class-name : com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource

